name: Build Shuttle Apps

on:
  push:
    branches:
      - master

jobs:
  build-dolapdere:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies for Dolapdere
        run: cd dolapdere && yarn install

      - name: Build Dolapdere
        run: cd dolapdere && yarn make
      
      - name: List output directories
        run: |
          Get-ChildItem -Path dolapdere\out -Recurse
          Get-ChildItem -Path dolapdere\out\my-app-64 -Recurse
          Get-ChildItem -Path dolapdere\out\installer64 -Recurse

      - name: Upload Dolapdere .exe as artifact
        uses: actions/upload-artifact@v2
        with:
          name: dolapdere-exe
          path: |
            dolapdere/out/dolapdere-win32-x64/dolapdere.exe
            dolapdere/out/make/squirrel.windows/x64/dolapdere-1.0.0\ Setup.exe
  
  build-santralistanbul:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies for santralistanbul
        run: cd santralistanbul && yarn install

      - name: Build santralistanbul
        run: cd santralistanbul && yarn make

      - name: Upload Santralistanbul .exe as artifact
        uses: actions/upload-artifact@v2
        with:
          name: santralistanbul-exe
          path: |
            santralistanbul/out/santralistanbul-win32-x64/santralistanbul.exe
            santralistanbul/out/make/squirrel.windows/x64/santralistanbul-1.0.0\ Setup.exe
  
  build-kustepe:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies for kustepe
        run: cd kustepe && yarn install

      - name: Build kustepe
        run: cd kustepe && yarn make

      - name: Upload Kustepe .exe as artifact
        uses: actions/upload-artifact@v2
        with:
          name: kustepe-exe
          path: |
            kustepe/out/kustepe-win32-x64/kustepe.exe
            kustepe/out/make/squirrel.windows/x64/kustepe-1.0.0\ Setup.exe